feat(git): add lumen for creating commit messages

diff --git a/bin/ai_commit b/bin/ai_commit
--- a/bin/ai_commit
+++ b/bin/ai_commit
@@ -20,8 +20,8 @@ magenta=$(tput setaf 5)
 cyan=$(tput setaf 6)
 white=$(tput setaf 7)
 
-if ! command -v aichat >/dev/null; then
-  printf "%sError: aichat not found in the system.\n" "$red"
+if ! command -v lumen >/dev/null; then
+  printf "%sError: lumen not found in the system.\n" "$red"
   exit 127
 fi
 
@@ -31,8 +31,7 @@ if [ -z "$git_diff" ]; then
   exit 1
 fi
 
-commit_message="$(aichat --role commit --no-stream \
-  "$git_diff" | fmt --width 90)"
+commit_message="$(lumen draft)"
 
 printf "%s$commit_message" "$white"
 printf "\n"
