fix(docker): Start docker VM first and always on macOS

diff --git a/bin/docker b/bin/docker
--- a/bin/docker
+++ b/bin/docker
@@ -51,7 +51,16 @@ install_docker_compose_plugin() {
 }
 
 if [ "$(uname -s)" = 'Darwin' ]; then
-  # prefer homebrew installed docker CLI
+  # in all cases, guest VM is required to run Docker daemon
+  if ! command -v limactl >/dev/null; then
+    echo "Error: limactl not found on macOS, cannot start Linux VM for docker."
+    exit 127
+  fi
+  if ! limactl shell "$VM" true >/dev/null 2>&1; then
+    limactl start "$HOME/.config/configent/lima/$VM.yaml" --tty=false ||
+      limactl start "$VM"
+  fi
+  # try homebrew installed docker CLI first on macOS
   if [ -x "/opt/homebrew/bin/docker" ]; then
     docker_bin_path="/opt/homebrew/bin/docker"
   elif [ -x "/usr/local/bin/docker" ]; then
@@ -66,15 +75,7 @@ if [ "$(uname -s)" = 'Darwin' ]; then
     fi
     "$docker_bin_path" "$@"
   else
-    if ! command -v limactl >/dev/null; then
-      echo "Error: limactl not found on macOS, cannot start Linux VM for docker."
-      exit 127
-    fi
-    if ! limactl shell "$VM" true >/dev/null 2>&1; then
-      limactl start "$HOME/.config/configent/lima/$VM.yaml" --tty=false ||
-        limactl start "$VM"
-    fi
-    # pass arguments to this exact same script on the guest VM
+    # no docker CLI found on macOS -> call this script on the Linux guest VM
     limactl shell "$VM" ~/configent/bin/docker "$@"
   fi
 else
