Reformat scripts with shfmt

diff --git a/bin/install_apps_apk b/bin/install_apps_apk
--- a/bin/install_apps_apk
+++ b/bin/install_apps_apk
@@ -3,29 +3,29 @@
 trap "printf '\nCaught ^C from user - exiting now' ; exit 130" INT
 
 if [ "$(id -u)" = 0 ]; then
-    SUDO=''
-elif which sudo >/dev/null 2>&1 ; then
-    SUDO='sudo DEBIAN_FRONTEND=noninteractive'
+  SUDO=''
+elif which sudo >/dev/null 2>&1; then
+  SUDO='sudo DEBIAN_FRONTEND=noninteractive'
 
-    # Ask sudo password upfront
-    sudo -v
+  # Ask sudo password upfront
+  sudo -v
 
-    # Keep sudo alive until the script has finished
-    while true; do
-      sudo -n true
-      sleep 60
-      kill -0 "$$" || exit
-    done 2>/dev/null &
+  # Keep sudo alive until the script has finished
+  while true; do
+    sudo -n true
+    sleep 60
+    kill -0 "$$" || exit
+  done 2>/dev/null &
 else
-    printf "\nERROR: User is non-root and sudo not available, cannot proceed.\n"
-    exit 1
+  printf "\nERROR: User is non-root and sudo not available, cannot proceed.\n"
+  exit 1
 fi
 
 # Update package lists
 $SUDO apk update
 
 # Certificates
-$SUDO apk add ca-certificates 
+$SUDO apk add ca-certificates
 
 # Cryptography
 $SUDO apk add gnupg
@@ -37,7 +37,7 @@ $SUDO apk add build-base gcompat ncurses \
 # Utils
 $SUDO apk add bash coreutils curl bind-tools file findutils \
   git htop procps zip unzip wget whois
-  
+
 # macOS pbcopy/pbpaste like experience
 #$SUDO apk add xsel
 
diff --git a/bin/install_apps_apt b/bin/install_apps_apt
--- a/bin/install_apps_apt
+++ b/bin/install_apps_apt
@@ -3,25 +3,25 @@
 trap "printf '\nCaught ^C from user - exiting now' ; exit 130" INT
 
 if [ "$(id -u)" = 0 ]; then
-    SUDO=''
-    SUDOEULA=''
-    export DEBIAN_FRONTEND=noninteractive
-elif which sudo >/dev/null 2>&1 ; then
-    SUDO='sudo DEBIAN_FRONTEND=noninteractive'
-    SUDOEULA='sudo ACCEPT_EULA=Y'
+  SUDO=''
+  SUDOEULA=''
+  export DEBIAN_FRONTEND=noninteractive
+elif which sudo >/dev/null 2>&1; then
+  SUDO='sudo DEBIAN_FRONTEND=noninteractive'
+  SUDOEULA='sudo ACCEPT_EULA=Y'
 
-    # Ask sudo password upfront
-    sudo -v
+  # Ask sudo password upfront
+  sudo -v
 
-    # Keep sudo alive until the script has finished
-    while true; do
-      sudo -n true
-      sleep 60
-      kill -0 "$$" || exit
-    done 2>/dev/null &
+  # Keep sudo alive until the script has finished
+  while true; do
+    sudo -n true
+    sleep 60
+    kill -0 "$$" || exit
+  done 2>/dev/null &
 else
-    printf "\nERROR: User is non-root and sudo not available, cannot proceed.\n"
-    exit 1
+  printf "\nERROR: User is non-root and sudo not available, cannot proceed.\n"
+  exit 1
 fi
 
 # Update package lists
@@ -31,7 +31,7 @@ $SUDOEULA apt-get update
 $SUDO apt-get install -y apt-transport-https
 
 # Certificates
-$SUDO apt-get install -y ca-certificates 
+$SUDO apt-get install -y ca-certificates
 
 # Cryptography
 $SUDO apt-get install -y gnupg
diff --git a/bin/install_apps_snap b/bin/install_apps_snap
--- a/bin/install_apps_snap
+++ b/bin/install_apps_snap
@@ -3,22 +3,22 @@
 trap "echo -e '\nCaught ^C from user - exiting now' ; exit 130" SIGINT
 
 if [ "$(id -u)" = 0 ]; then
-    SUDO=''
+  SUDO=''
 elif which sudo &>/dev/null; then
-    SUDO='sudo'
+  SUDO='sudo'
 
-    # Ask sudo password upfront
-    sudo -v
+  # Ask sudo password upfront
+  sudo -v
 
-    # Keep sudo alive until the script has finished
-    while true; do
-      sudo -n true
-      sleep 60
-      kill -0 "$$" || exit
-    done 2>/dev/null &
+  # Keep sudo alive until the script has finished
+  while true; do
+    sudo -n true
+    sleep 60
+    kill -0 "$$" || exit
+  done 2>/dev/null &
 else
-    echo "ERROR: User is non-root and sudo is not available, cannot proceed."
-    exit 1
+  echo "ERROR: User is non-root and sudo is not available, cannot proceed."
+  exit 1
 fi
 
 # Core
diff --git a/bin/install_apps_yum b/bin/install_apps_yum
--- a/bin/install_apps_yum
+++ b/bin/install_apps_yum
@@ -3,22 +3,22 @@
 trap "printf '\nCaught ^C from user - exiting now' ; exit 130" INT
 
 if [ "$(id -u)" = 0 ]; then
-    SUDO=''
-elif which sudo >/dev/null 2>&1 ; then
-    SUDO='sudo'
+  SUDO=''
+elif which sudo >/dev/null 2>&1; then
+  SUDO='sudo'
 
-    # Ask sudo password upfront
-    sudo -v
+  # Ask sudo password upfront
+  sudo -v
 
-    # Keep sudo alive until the script has finished
-    while true; do
-      sudo -n true
-      sleep 60
-      kill -0 "$$" || exit
-    done 2>/dev/null &
+  # Keep sudo alive until the script has finished
+  while true; do
+    sudo -n true
+    sleep 60
+    kill -0 "$$" || exit
+  done 2>/dev/null &
 else
-    printf "\nERROR: User is non-root and sudo not available, cannot proceed.\n"
-    exit 1
+  printf "\nERROR: User is non-root and sudo not available, cannot proceed.\n"
+  exit 1
 fi
 
 # Update package lists
@@ -28,7 +28,7 @@ $SUDO yum check-update -y
 $SUDO yum install -y epel-release
 
 # Certificates
-$SUDO yum install -y ca-certificates 
+$SUDO yum install -y ca-certificates
 
 # Cryptography
 $SUDO yum install -y gnupg
@@ -57,6 +57,6 @@ $SUDO loginctl enable-linger "$USER"
 
 # Snap
 $SUDO yum install -y fuse squashfuse # docker requirement for snap
-$SUDO yum install -y kernel-modules # VM requirement for snap
+$SUDO yum install -y kernel-modules  # VM requirement for snap
 $SUDO yum install -y snapd
 $SUDO ln -s /var/lib/snapd/snap /snap
