fix(lessfilter): Fix exit code to pass to lesspipe

diff --git a/bin/lessfilter b/bin/lessfilter
--- a/bin/lessfilter
+++ b/bin/lessfilter
@@ -20,4 +20,7 @@ if has_cmd lsd && [ -d "$1" ]; then
 elif has_cmd bat && [ "$category" = text ]; then
   # colorize any text file always, something which lesspipe.sh does not do
   bat --color=always --style=plain --paging=never "$1"
+else
+  # any non-zero exit code leaves the filtering to lesspipe.sh
+  exit 1
 fi
