fix(nerdctl): Add check for lima installed

diff --git a/bin/nerdctl b/bin/nerdctl
--- a/bin/nerdctl
+++ b/bin/nerdctl
@@ -13,11 +13,15 @@
 : "${VM:="debian"}"
 
 if [ "$(uname -s)" = 'Darwin' ]; then
+  if ! command -v limactl >/dev/null; then
+    echo "Error: limactl not found on macOS, cannot start Linux VM for nerdctl."
+    exit 127
+  fi
   if ! limactl shell "$VM" true >/dev/null 2>&1; then
     limactl start "$HOME/local/etc/lima/$VM.yaml" --tty=false ||
       limactl start "$VM"
   fi
-  # forward to the same script on the guest VM
+  # pass arguments to this exact same script on the guest VM
   limactl shell "$VM" "$HOME/local/bin/nerdctl" $@
 else
   # shellcheck disable=SC2155  # will not declare separately
